global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'main1'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'main2'
    static_configs:
      - targets: ['localhost:8082']

  - job_name: 'jenkins'
    static_configs:
      - targets: ['localhost:8083']

  - job_name: 'sub1'
    static_configs:
      - targets: ['13.124.72.122:8082']

  - job_name: 'sub2'
    static_configs:
      - targets: ['13.124.72.122:8082']

